/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package framePrincipal;

import dtos.salida.InmuebleSalidaDTO;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import paneles.PantallaConsultarSolicitudes;
import paneles.PantallaGenerarOrden;
import paneles.PantallaGestorArrendamiento;
import paneles.PantallaRegistrarInquilino;
import paneles.PantallaResumenPlanPagos;

/**
 *
 * @author joser
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private JPanel contenedor;
    public ControlObjetos controlObjetos = new ControlObjetos();
    
    private CardLayout cardLayout;
    private PantallaGestorArrendamiento gestorArrendamiento;
    
    private PantallaRegistrarInquilino registrarInquilino;
    private PantallaResumenPlanPagos planPagos;
    
    private PantallaGenerarOrden generarOrden;
    private PantallaConsultarSolicitudes consultarSolicitudes;
//    private PantallaSolicitudPendiente consultarPendientes;
    
//    private PantallaGestorContratos gestorContratos;
    

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        //initComponents();
        setTitle("Sistema inmobiliaria");
        setSize(1280, 720);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        
        iniciarComponentes();
        
        this.setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    private void iniciarComponentes() {
        
        
        cardLayout = new CardLayout();
        contenedor = new JPanel(cardLayout);

        gestorArrendamiento = new PantallaGestorArrendamiento(this, controlObjetos);
        generarOrden = new PantallaGenerarOrden();
        consultarSolicitudes = new PantallaConsultarSolicitudes();
        registrarInquilino = new PantallaRegistrarInquilino(this, controlObjetos);
        planPagos = new PantallaResumenPlanPagos(this, controlObjetos);

        contenedor.add(gestorArrendamiento, "PanelGestorArrendamiento");
        contenedor.add(generarOrden, "PanelGenerarOrden");
        contenedor.add(consultarSolicitudes, "PanelConsultarSolicitudes");
        contenedor.add(registrarInquilino, "PanelRegistrarInquilino");
        contenedor.add(planPagos, "PanelPlanPagos");
        

        this.add(contenedor);
        
        
        JMenuBar bar = new JMenuBar();
        JMenu menu = new JMenu("Gestor Arrendamiento");
        JMenuItem item1 = new JMenuItem("Registrar arrendamiento");
        JMenu menu2 = new JMenu("Gestor Servicios");
        JMenuItem item2 = new JMenuItem("Generar orden");
        JMenuItem item3 = new JMenuItem("ConsultarSolicitudes");
        JMenu menu3 = new JMenu("Gestor contratos");
        JMenuItem item4 = new JMenuItem("Finalizar contrato");
                
        
        item1.addActionListener(e -> {
            refrescarPantallaGestor();
            cardLayout.show(contenedor, "PanelGestorArrendamiento");
        });
        item2.addActionListener(e -> cardLayout.show(contenedor, "PanelGenerarOrden"));
        item3.addActionListener(e -> cardLayout.show(contenedor, "PanelConsultarSolicitudes"));
        
        menu.add(item1);
        menu2.add(item2);
        menu2.add(item3);
        menu3.add(item4);
        bar.add(menu);
        bar.add(menu2);
        bar.add(menu3);
        this.setJMenuBar(bar);
    }
    
    
    public void cambiarPantalla(String nombre) {
        cardLayout.show(contenedor, nombre);
    }

    public void refrescarPantallaGestor() {
        if (gestorArrendamiento != null) {
            gestorArrendamiento.actualizarVista();
        }
    }
    
    public void refrescarPantallaResumenPlan(){
        if (planPagos != null) {
            planPagos.refrescarDatos();
        }
    
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
