/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dtos.entrada.RegistrarContratoDTO;
import framePrincipal.ControlObjetos;
import framePrincipal.FramePrincipal;
import java.awt.Color;
import java.awt.Font;
import java.time.Instant;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import objetosNegocio.ContratoBO;
import objetosNegocio.IContratoBO;
import objetosNegocio.IInmuebleBO;
import objetosNegocio.InmuebleBO;

/**
 *
 * @author joser
 */
public class PantallaResumenPlanPagos extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;
    public ControlObjetos controlObjetos;
    private IInmuebleBO inmuebleBO = new InmuebleBO();
    private IContratoBO contratoBO = new ContratoBO();
    
    private JLabel lblDescripcion;
    
    public JLabel lblDeposito, lblGastosAdmin, lblMensualidad, lblSeguro, lblTotal, lblFechas;
    
    private Float total;
    
    /**
     * Creates new form PantallaResumenPlanPagos
     */
    public PantallaResumenPlanPagos(FramePrincipal framePrincipal, ControlObjetos controlObjetos ) {
        this.framePrincipal = framePrincipal;
        this.controlObjetos = controlObjetos;
        setLayout(null);
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        Font fuenteTitulo = new Font("Arial", Font.BOLD, 28);
        Font fuenteTexto = new Font("Arial", Font.PLAIN, 22);
        Font fuenteLabels = new Font("Arial", Font.BOLD, 18);
        LineBorder bordeCaja = new LineBorder(Color.GRAY, 1);
        Color colorFondoCaja = new Color(225, 225, 225);

        // Título
        JLabel lblTitulo = new JLabel("Plan de pagos");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setBounds(60, 30, 400, 40);
        add(lblTitulo);

        // Descripción dinámica: "El inquilino {nombre} hará renta..."
        lblDescripcion = new JLabel("El inquilino hará renta de la propiedad ubicada en...");
        lblDescripcion.setFont(fuenteTexto);
        lblDescripcion.setBounds(60, 80, 1100, 30);
        add(lblDescripcion);

        // --- COLUMNA IZQUIERDA ---
        crearSeccion(60, 130, "Depósito:", lblDeposito = new JLabel(" "), fuenteLabels, bordeCaja, colorFondoCaja);
        crearSeccion(60, 240, "Mensualidad regular:", lblMensualidad = new JLabel(" "), fuenteLabels, bordeCaja, colorFondoCaja);
        crearSeccion(60, 350, "Total a pagar hoy:", lblTotal = new JLabel(" "), fuenteLabels, bordeCaja, colorFondoCaja);

        // --- COLUMNA DERECHA ---
        crearSeccion(600, 130, "Costos administrativos:", lblGastosAdmin = new JLabel(" "), fuenteLabels, bordeCaja, colorFondoCaja);
        crearSeccion(600, 240, "Seguro contra daños:", lblSeguro = new JLabel(" "), fuenteLabels, bordeCaja, colorFondoCaja);
        crearSeccion(600, 350, "Fechas de pago:", lblFechas = new JLabel(" "), fuenteLabels, bordeCaja, colorFondoCaja);

        // --- BOTONES ---
        JButton btnCancelar = new JButton("Cancelar");
        btnCancelar.setBounds(200, 550, 300, 60);
        btnCancelar.setBackground(new Color(140, 140, 140));
        btnCancelar.setFont(fuenteTexto);
        add(btnCancelar);

        JButton btnConcluir = new JButton("Concluir arrendamiento");
        btnConcluir.setBounds(650, 550, 350, 60);
        btnConcluir.setBackground(new Color(140, 140, 140));
        btnConcluir.setFont(fuenteTexto);
        add(btnConcluir);

        // Acción Volver
        btnCancelar.addActionListener(e -> framePrincipal.cambiarPantalla("PanelGestorArrendamiento"));

        btnConcluir.addActionListener(e -> {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Desea finalizar el registro del arrendamiento?",
                    "Confirmar Operación",
                    JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    
                    if (controlObjetos.getInquilino().getIngresoMensual() < total) {
                        JOptionPane.showMessageDialog(this, "El inquilino no cumple con la solvencia económica.");
                        return;
                    }
                    
                    inmuebleBO.registrarInquilino(controlObjetos.getInmuebleSeleccionado().idInmueble(), controlObjetos.getInquilino());
                    RegistrarContratoDTO contrato = new RegistrarContratoDTO();
                    contrato.setFechaInicio(Instant.now());
                    contrato.setIdInmueble(controlObjetos.getInmuebleSeleccionado().idInmueble());
                    
                    contratoBO.crearContrato(contrato);
                    JOptionPane.showMessageDialog(this, "¡Arrendamiento registrado con éxito!");
                    
                    
                    controlObjetos.setInmuebleSeleccionado(null);
                    controlObjetos.setInquilino(null);
                    
                    framePrincipal.refrescarPantallaGestor();
                    framePrincipal.cambiarPantalla("PanelGestorArrendamiento");

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }
    
    
    private void crearSeccion(int x, int y, String titulo, JLabel labelDato, Font fuente, LineBorder borde, Color fondo) {
        JLabel lblTituloSec = new JLabel(titulo);
        lblTituloSec.setFont(fuente);
        lblTituloSec.setBounds(x, y, 400, 30);
        add(lblTituloSec);

        labelDato.setBounds(x, y + 40, 450, 50);
        labelDato.setOpaque(true);
        labelDato.setBackground(fondo);
        labelDato.setBorder(BorderFactory.createCompoundBorder(borde, BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        add(labelDato);
    }

    public void refrescarDatos() {
        Float gastosAdmin;
        Float mensualidad;
        Float deposito;
        Float seguro = 2000f;
        total = 0f;
        lblDescripcion.setText("El inquilino " +
                controlObjetos.getInquilino().getNombre() +
                controlObjetos.getInquilino().getApellidoPaterno() +
                " hará renta del inmueble ubicado en: " + controlObjetos.getInmuebleSeleccionado().direccion());
        
        if (controlObjetos.getInmuebleSeleccionado().tipo() == "residencial") {
            //Residencial deposito un mes de renta 
            mensualidad = controlObjetos.getInmuebleSeleccionado().rentaMensual();
            deposito = mensualidad;
            lblDeposito.setText(controlObjetos.getInmuebleSeleccionado().rentaMensual().toString() );
            gastosAdmin = controlObjetos.getInmuebleSeleccionado().rentaMensual() * 0.10f;
            lblGastosAdmin.setText(gastosAdmin.toString());
            lblMensualidad.setText(controlObjetos.getInmuebleSeleccionado().rentaMensual().toString());
            lblSeguro.setText(seguro.toString());
            total = gastosAdmin + seguro + mensualidad + deposito;
            lblTotal.setText(total.toString());
            Instant fechaHoy = Instant.now();
            lblFechas.setText(fechaHoy.toString());
            
            
        }
        else{
            //comercial deposito dos meses de renta
            mensualidad = controlObjetos.getInmuebleSeleccionado().rentaMensual();
            deposito = mensualidad * 2;
            lblDeposito.setText(controlObjetos.getInmuebleSeleccionado().rentaMensual().toString() );
            gastosAdmin = controlObjetos.getInmuebleSeleccionado().rentaMensual() * 0.10f;
            lblGastosAdmin.setText(gastosAdmin.toString());
            lblMensualidad.setText(controlObjetos.getInmuebleSeleccionado().rentaMensual().toString());
            lblSeguro.setText(seguro.toString());
            total = gastosAdmin + seguro + mensualidad + deposito;
            lblTotal.setText(total.toString());
            Instant fechaHoy = Instant.now();
            lblFechas.setText(fechaHoy.toString());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
