/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dtos.salida.InmuebleSalidaDTO;
import framePrincipal.FramePrincipal;
import objetosNegocio.IInmuebleBO;
import objetosNegocio.InmuebleBO;

/**
 *
 * @author joser
 */
public class PantallaRegistrarInquilino extends javax.swing.JPanel {

    private FramePrincipal frame;
    private static IInmuebleBO inmuebleBO;
    private InmuebleSalidaDTO inmuebleSeleccionado;
    
    /**
     * Creates new form PantallaRegistrarInquilino
     */
    public PantallaRegistrarInquilino() {
        this.frame = frame;
        inmuebleBO = new InmuebleBO();
        iniciarComponentes();
    }

    public void recibirDTO(InmuebleSalidaDTO inmueble){
        this.inmuebleSeleccionado = inmueble;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
