/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dtos.comunes.ContratoDTO;
import dtos.salida.ContratoSalidaDTO;
import dtos.salida.InmuebleSalidaDTO;
import excepcion.NegocioException;
import framePrincipal.ControlObjetos;
import framePrincipal.FramePrincipal;
import java.awt.Color;
import java.awt.Font;
import java.time.Instant;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import objetosNegocio.ContratoBO;
import objetosNegocio.IContratoBO;
import objetosNegocio.IInmuebleBO;
import objetosNegocio.InmuebleBO;

/**
 *
 * @author joser
 */
public class PantallaFinalizarContrato extends javax.swing.JPanel {

    FramePrincipal framePrincipal;
    ControlObjetos controlObjetos;
    public JComboBox<String> cbPropiedadesRentadas, cbMotivo;
    public JTextArea txtObservaciones;
    public JButton btnFinalizar;
    List<InmuebleSalidaDTO> inmueblesArrendados;
    IInmuebleBO inmuebleBO = new InmuebleBO();
    IContratoBO contratoBO = new ContratoBO();

    /**
     * Creates new form PantallaFinalizarContrato
     */
    public PantallaFinalizarContrato(FramePrincipal framePrincipal, ControlObjetos controlObjetos) {
        this.controlObjetos = controlObjetos;
        this.framePrincipal = framePrincipal;
        setLayout(null);
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        Font fuenteTitulo = new Font("Arial", Font.BOLD, 26);
        Font fuenteLabels = new Font("Arial", Font.PLAIN, 22);
        Font fuenteCampos = new Font("Arial", Font.PLAIN, 18);

        // --- TÍTULO ---
        JLabel lblTitulo = new JLabel("Finalizar contrato");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setBounds(50, 40, 400, 40);
        add(lblTitulo);

        // --- COMBO PROPIEDADES RENTADAS ---
        JLabel lblPropiedades = new JLabel("Propiedades rentadas:");
        lblPropiedades.setFont(fuenteLabels);
        lblPropiedades.setBounds(50, 90, 400, 30);
        add(lblPropiedades);

        cbPropiedadesRentadas = new JComboBox<>();
        cbPropiedadesRentadas.setBounds(50, 130, 800, 45);
        cbPropiedadesRentadas.setFont(fuenteCampos);
        cbPropiedadesRentadas.setBackground(Color.WHITE);
        add(cbPropiedadesRentadas);

        // --- MOTIVO FINALIZACIÓN ---
        JLabel lblMotivo = new JLabel("Motivo finalizacion:");
        lblMotivo.setFont(fuenteLabels);
        lblMotivo.setBounds(50, 210, 300, 30);
        add(lblMotivo);

        // OPCIONES ACTUALIZADAS
        String[] motivos = {
            "Fin de contrato",
            "Terminación anticipada",
            "Cambio de domicilio del arrendatario",
            "Incumplimiento de pago",
            "Otros"
        };

        cbMotivo = new JComboBox<>(motivos);
        // Lo hacemos un poco más ancho (450) para que se lea bien el texto largo
        cbMotivo.setBounds(50, 250, 450, 40);
        cbMotivo.setFont(fuenteCampos);
        cbMotivo.setBackground(Color.WHITE);
        add(cbMotivo);

        // --- OBSERVACIONES GENERALES ---
        JLabel lblObs = new JLabel("Observaciones generales:");
        lblObs.setFont(fuenteLabels);
        lblObs.setBounds(50, 330, 400, 30);
        add(lblObs);

        txtObservaciones = new JTextArea();
        txtObservaciones.setFont(fuenteCampos);
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setWrapStyleWord(true);

        JScrollPane scrollObs = new JScrollPane(txtObservaciones);
        scrollObs.setBounds(50, 370, 700, 200);
        add(scrollObs);

        // --- BOTÓN FINALIZAR ---
        btnFinalizar = new JButton("Finalizar");
        btnFinalizar.setBounds(850, 500, 280, 60);
        btnFinalizar.setFont(fuenteLabels);
        btnFinalizar.setBackground(new Color(140, 140, 140));
        btnFinalizar.setFocusable(false);
        add(btnFinalizar);

        btnFinalizar.addActionListener(e -> {
            if (cbPropiedadesRentadas.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione una propiedad para finalizar el contrato.");
                return;
            }

            int confirmar = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea finalizar este contrato? Esta acción liberará la propiedad.",
                    "Confirmar finalización", JOptionPane.YES_NO_OPTION);

            if (confirmar == JOptionPane.YES_OPTION) {
                
                try {
                    String seleccion = (String) cbPropiedadesRentadas.getSelectedItem();
                    InmuebleSalidaDTO inmueble = obtenerDTO(seleccion);
                    ContratoDTO contrato = new ContratoDTO();
                    ContratoSalidaDTO contratoEncontrado = contratoBO.buscarContrato(inmueble.idInmueble());
                    
                    contrato.setFechaInicio(contratoEncontrado.fechaInicio());
                    contrato.setFechaFin(Instant.now());
                    contrato.setIdInmueble(contratoEncontrado.idInmueble());
                    contrato.setAdeudo(0f);
                    contrato.setMotivo((String)cbMotivo.getSelectedItem());
                    contrato.setObservaciones(txtObservaciones.getText());
                    
                    System.out.println("llegamos aqui");
                    contratoBO.editarContrato(contrato);
                    
                    inmuebleBO.quitarInquilino(inmueble.idInmueble());

                } catch (NegocioException ex) {
                    System.out.println(ex.getMessage());
                }


                
                JOptionPane.showMessageDialog(this, "Contrato finalizado exitosamente.");

                // IMPORTANTE: Refrescar las listas después de liberar la propiedad
                framePrincipal.refrescarPantallaGestor();
                limpiarCampos();
                framePrincipal.cambiarPantalla("PanelGestorArrendamiento");
            }
        });
    }

    public void actualizarListaRentadas() {
        cbPropiedadesRentadas.removeAllItems();
        try{
        inmueblesArrendados = inmuebleBO.listarInmueblesRentados();
        }catch(NegocioException ex){
            System.out.println(ex.getMessage());
        }
                
        for (InmuebleSalidaDTO item : inmueblesArrendados) {
            cbPropiedadesRentadas.addItem(item.direccion());
        }
    }

    private void limpiarCampos() {
        txtObservaciones.setText("");
        cbMotivo.setSelectedIndex(0);
    }
    
    private InmuebleSalidaDTO obtenerDTO(String calle) {
        for (InmuebleSalidaDTO inmueble : inmueblesArrendados) {
            if (inmueble.direccion().equalsIgnoreCase(calle)) {
                return inmueble;
            }
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
