/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dtos.salida.InmuebleSalidaDTO;
import dtos.salida.MantenimientoSalidaDTO;
import excepcion.NegocioException;
import framePrincipal.ControlObjetos;
import framePrincipal.FramePrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.IMantenimientoBO;
import objetosNegocio.MantenimientoBO;

/**
 *
 * @author joser
 */
public class PantallaSolicitudPendientes extends javax.swing.JPanel {
    FramePrincipal framePrincipal;
    ControlObjetos controlObjetos;
    
    public JTable tablaSolicitudes;
    public DefaultTableModel modeloTabla;
    public JButton btnSeleccionar;
    
    List<MantenimientoSalidaDTO> mantenimientosPendientes;
    
    
    IMantenimientoBO mantenimientoBO = new MantenimientoBO();
    
    /**
     * Creates new form PantallaSolicitudPendientes
     */
    public PantallaSolicitudPendientes(FramePrincipal framePrincipal, ControlObjetos controlObjetos) {
        this.framePrincipal = framePrincipal;
        this.controlObjetos = controlObjetos;
        
        setLayout(null);
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        Font fuenteTitulo = new Font("Arial", Font.BOLD, 26);
        Font fuenteLabels = new Font("Arial", Font.PLAIN, 22);

        // --- TÍTULO ---
        JLabel lblTitulo = new JLabel("Consultar solicitudes de mantenimiento:");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setBounds(50, 40, 600, 40);
        add(lblTitulo);

        JLabel lblSolicitudes = new JLabel("Solicitudes:");
        lblSolicitudes.setFont(fuenteLabels);
        lblSolicitudes.setBounds(50, 90, 200, 30);
        add(lblSolicitudes);

        // --- CONFIGURACIÓN DE LA TABLA ---
        String[] columnas = {"Dirección", "Descripción", "Prioridad", "Costo"};
        // El modelo de la tabla evita que las celdas sean editables directamente
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaSolicitudes = new JTable(modeloTabla);
        tablaSolicitudes.setFont(new Font("Arial", Font.PLAIN, 16));
        tablaSolicitudes.setRowHeight(30); // Filas más altas para que respiren
        tablaSolicitudes.getTableHeader().setFont(new Font("Arial", Font.BOLD, 18));

        // JScrollPane para que la tabla tenga barras de desplazamiento y se vea profesional
        JScrollPane scrollPane = new JScrollPane(tablaSolicitudes);
        scrollPane.setBounds(50, 140, 1000, 350); 
        add(scrollPane);

        // --- BOTÓN SELECCIONAR ---
        btnSeleccionar = new JButton("Seleccionar");
        btnSeleccionar.setBounds(850, 520, 200, 50);
        btnSeleccionar.setFont(fuenteLabels);
        btnSeleccionar.setBackground(new Color(140, 140, 140));
        btnSeleccionar.setFocusable(false);
        add(btnSeleccionar);

        // --- LÓGICA DEL BOTÓN ---
        btnSeleccionar.addActionListener(e -> {
            int filaSeleccionada = tablaSolicitudes.getSelectedRow();
            
            if (filaSeleccionada != -1) {
                
                String direccion = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
                
                System.out.println("Seleccionado: " + direccion);
                

                JOptionPane.showMessageDialog(this, "Redirigiendo a detalles de: " + direccion);
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una solicitud de la tabla.");
            }
        });
    }
    
    public void cargarTabla() {
        modeloTabla.setRowCount(0);
        try{
            mantenimientosPendientes = mantenimientoBO.listarMantenimientosPendientes();
        }
        catch(NegocioException ex){
            System.out.println(ex.getMessage());
        }
        
        for (MantenimientoSalidaDTO mant : mantenimientosPendientes) {

                Object[] fila = {
                    mant.idInmueble(),
                    mant.descripcion(),
                    mant.prioridad(),
                    mant.costo()
                };
                
                modeloTabla.addRow(fila);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
