/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dtos.comunes.MantenimientoDTO;
import dtos.salida.InmuebleSalidaDTO;
import dtos.salida.MantenimientoSalidaDTO;
import excepcion.NegocioException;
import framePrincipal.ControlObjetos;
import framePrincipal.FramePrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.IInmuebleBO;
import objetosNegocio.IMantenimientoBO;
import objetosNegocio.InmuebleBO;
import objetosNegocio.MantenimientoBO;

/**
 *
 * @author joser
 */
public class PantallaSolicitudPendientes extends javax.swing.JPanel {
    FramePrincipal framePrincipal;
    ControlObjetos controlObjetos;

    public JComboBox<MantenimientoSalidaDTO> cbSolicitudes;
    public JTextField txtDireccion;
    public JTextField txtDescripcion;
    public JTextArea txtNotasAdicionales;
    public JButton btnCancelarOrden, btnCompletarOrden;

    List<MantenimientoSalidaDTO> mantenimientosPendientes;
    
    IInmuebleBO inmuebleBO = new InmuebleBO();
    IMantenimientoBO mantenimientoBO = new MantenimientoBO();
    
    /**
     * Creates new form PantallaSolicitudPendientes
     */
    public PantallaSolicitudPendientes(FramePrincipal framePrincipal, ControlObjetos controlObjetos) {
        this.framePrincipal = framePrincipal;
        this.controlObjetos = controlObjetos;
        setLayout(null);
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        Font fuenteTitulo = new Font("Arial", Font.BOLD, 24);
        Font fuenteLabels = new Font("Arial", Font.PLAIN, 20);
        Font fuenteCampos = new Font("Arial", Font.PLAIN, 18);
        Color colorBloqueado = new Color(230, 230, 230);

        // --- TÍTULO ---
        JLabel lblTitulo = new JLabel("Generar orden de servicio:");
        lblTitulo.setFont(fuenteTitulo);
        lblTitulo.setBounds(50, 30, 400, 35);
        add(lblTitulo);

        // --- COMBOBOX SOLICITUDES ---
        JLabel lblSolicitudes = new JLabel("Solicitudes pendientes:");
        lblSolicitudes.setFont(fuenteLabels);
        lblSolicitudes.setBounds(50, 80, 400, 25);
        add(lblSolicitudes);

        cbSolicitudes = new JComboBox<>(); // <--- Instancia primero
        cbSolicitudes.setBounds(50, 115, 600, 40);
        cbSolicitudes.setFont(fuenteCampos);
        cbSolicitudes.setBackground(Color.WHITE);
        add(cbSolicitudes);

        // --- DIRECCIÓN ---
        JLabel lblDireccion = new JLabel("Dirección:");
        lblDireccion.setFont(fuenteLabels);
        lblDireccion.setBounds(50, 175, 200, 25);
        add(lblDireccion);

        txtDireccion = new JTextField(); // <--- Instancia primero
        txtDireccion.setBounds(50, 210, 380, 45);
        txtDireccion.setFont(fuenteCampos);
        txtDireccion.setEditable(false);
        txtDireccion.setBackground(colorBloqueado);
        add(txtDireccion);


        // --- DESCRIPCIÓN ---
        JLabel lblDesc = new JLabel("Descripción:");
        lblDesc.setFont(fuenteLabels);
        lblDesc.setBounds(50, 275, 200, 25);
        add(lblDesc);

        txtDescripcion = new JTextField(); // <--- Instancia primero
        txtDescripcion.setBounds(50, 310, 840, 45);
        txtDescripcion.setFont(fuenteCampos);
        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(colorBloqueado);
        add(txtDescripcion);

        // --- NOTAS ADICIONALES ---
        JLabel lblNotas = new JLabel("Notas adicionales:");
        lblNotas.setFont(fuenteLabels);
        lblNotas.setBounds(50, 375, 250, 25);
        add(lblNotas);

        txtNotasAdicionales = new JTextArea(); // <--- Instancia primero
        txtNotasAdicionales.setFont(fuenteCampos);
        txtNotasAdicionales.setLineWrap(true);
        txtNotasAdicionales.setWrapStyleWord(true);

        JScrollPane scrollNotas = new JScrollPane(txtNotasAdicionales);
        scrollNotas.setBounds(50, 410, 600, 140);
        add(scrollNotas);

        // --- BOTONES ---
        btnCancelarOrden = new JButton("Cancelar orden");
        btnCancelarOrden.setBounds(680, 420, 220, 45);
        btnCancelarOrden.setFont(new Font("Arial", Font.PLAIN, 18));
        btnCancelarOrden.setBackground(new Color(160, 160, 160));
        add(btnCancelarOrden);

        btnCompletarOrden = new JButton("Completar orden");
        btnCompletarOrden.setBounds(680, 490, 220, 45);
        btnCompletarOrden.setFont(new Font("Arial", Font.PLAIN, 18));
        btnCompletarOrden.setBackground(new Color(160, 160, 160));
        add(btnCompletarOrden);

        // --- EVENTO DEL COMBOBOX ---
        cbSolicitudes.addActionListener(e -> actualizarDetalles());
        
        btnCancelarOrden.addActionListener(e -> {
            MantenimientoSalidaDTO seleccionado = (MantenimientoSalidaDTO) cbSolicitudes.getSelectedItem();

            if (seleccionado == null) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una solicitud para cancelar.");
                return;
            }

            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea cancelar esta solicitud de mantenimiento?",
                    "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    MantenimientoDTO mantenimientoActualizado = new MantenimientoDTO();
                    mantenimientoActualizado.setIdMantenimiento(seleccionado.getIdMantenimiento());
                    mantenimientoActualizado.setEstado("cancelado");
                    mantenimientoActualizado.setNotas(txtNotasAdicionales.getText());
                    
                    mantenimientoBO.finalizarMantenimiento(mantenimientoActualizado);

                    JOptionPane.showMessageDialog(this, "Solicitud cancelada con éxito.");
                    limpiarPantalla();
                    framePrincipal.cambiarPantalla("PanelGestorArrendamiento");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al cancelar: " + ex.getMessage());
                }
            }
        });

        // --- BOTÓN COMPLETAR ORDEN ---
        btnCompletarOrden.addActionListener(e -> {
            MantenimientoSalidaDTO seleccionado = (MantenimientoSalidaDTO) cbSolicitudes.getSelectedItem();
            String notas = txtNotasAdicionales.getText().trim();

            if (seleccionado == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una solicitud.");
                return;
            }

            if (notas.isEmpty()) {
                int continuar = JOptionPane.showConfirmDialog(this,
                        "¿Desea completar la orden sin agregar notas adicionales?",
                        "Notas vacías", JOptionPane.YES_NO_OPTION);
                if (continuar != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            try {
                MantenimientoDTO mantenimientoActualizado = new MantenimientoDTO();
                mantenimientoActualizado.setIdMantenimiento(seleccionado.getIdMantenimiento());
                mantenimientoActualizado.setEstado("completado");
                mantenimientoActualizado.setNotas(txtNotasAdicionales.getText());

                mantenimientoBO.finalizarMantenimiento(mantenimientoActualizado);

                JOptionPane.showMessageDialog(this, "Solicitud completada con éxito.");
                limpiarPantalla();
                framePrincipal.cambiarPantalla("PanelGestorArrendamiento");

                JOptionPane.showMessageDialog(this, "Orden de servicio completada exitosamente.");

                framePrincipal.refrescarPantallaGestor();
                framePrincipal.cambiarPantalla("PanelGestorArrendamiento");
                limpiarPantalla();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al completar la orden: " + ex.getMessage());
            }
        });
    }


    public void cargarSolicitudes() {
        System.out.println("hola");
        
        try{
            mantenimientosPendientes = mantenimientoBO.listarMantenimientosPendientes();
            System.out.println("Lista solicitudes actualizada.");
        }
        catch(NegocioException ex){
            System.out.println(ex.getMessage());
        }
        
        cbSolicitudes.removeAllItems();
        for (MantenimientoSalidaDTO m : mantenimientosPendientes) {
            cbSolicitudes.addItem(m);
        }
    }


    public void actualizarDetalles() {
        
        MantenimientoSalidaDTO seleccionado = (MantenimientoSalidaDTO) cbSolicitudes.getSelectedItem();
        try {
            InmuebleSalidaDTO objetoInmueble = inmuebleBO.buscarInmueblePorId(seleccionado.getIdInmueble());

            if (seleccionado != null) {
                txtDireccion.setText(objetoInmueble.direccion());
                txtDescripcion.setText(seleccionado.getDescripcion());
            }
        } catch (NegocioException ex) {
            System.out.println(ex.getMessage());
        }

        
    }

    
    private void limpiarPantalla() {
        txtDireccion.setText("");
        txtDescripcion.setText("");
        txtNotasAdicionales.setText("");
        if (cbSolicitudes.getItemCount() > 0) {
            cbSolicitudes.setSelectedIndex(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
