/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import dtos.salida.InmuebleSalidaDTO;
import excepcion.NegocioException;
import framePrincipal.FramePrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import objetosNegocio.IInmuebleBO;
import objetosNegocio.InmuebleBO;

/**
 *
 * @author joser
 */
public class PantallaGestorArrendamiento extends javax.swing.JPanel {
    
    private FramePrincipal frame;
    public JComboBox<String> cbPropiedades;
    public JLabel lblTipoDato, lblDireccionDato, lblRentaDato;
    public JButton btnRegistrar;
    private static IInmuebleBO inmuebleBO;
    private List<InmuebleSalidaDTO> listaInmuebles;
    private InmuebleSalidaDTO inmuebleSeleccionado;
    
    
    /**
     * Creates new form PantallaGestorArrendamiento
     * @param frame
     */
    public PantallaGestorArrendamiento(FramePrincipal frame) {
        this.frame = frame;
        setLayout(null);
        setBackground(new Color(211, 211, 211));
        this.inmuebleBO = new InmuebleBO();
        
        iniciarComponentes();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        Font fuenteLabels = new Font("Arial", Font.PLAIN, 24);
        Font fuenteDatos = new Font("Arial", Font.PLAIN, 20);
        LineBorder bordeCaja = new LineBorder(Color.GRAY, 1);
        Color colorFondoCaja = new Color(225, 225, 225);

        JLabel lblTituloCombo = new JLabel("Propiedades disponibles:");
        lblTituloCombo.setFont(fuenteLabels);
        lblTituloCombo.setBounds(80, 50, 400, 30);
        add(lblTituloCombo);
        
        try {
            cargarListaInmuebles();
        } catch (NegocioException ex) {
            System.out.println(ex.getMessage());
        }


        String[] arreglo = stringInmuebles().toArray(new String[0]);
        cbPropiedades = new JComboBox<>(arreglo);
        cbPropiedades.setBounds(80, 90, 800, 45);
        cbPropiedades.setBackground(Color.WHITE);
        add(cbPropiedades);

        JLabel lblTipo = new JLabel("Tipo:");
        lblTipo.setFont(fuenteLabels);
        lblTipo.setBounds(80, 180, 100, 30);
        add(lblTipo);

        lblTipoDato = new JLabel(" "); // Se llenará desde el back
        lblTipoDato.setBounds(80, 220, 430, 60);
        configurarEstiloCaja(lblTipoDato, fuenteDatos, bordeCaja, colorFondoCaja);
        add(lblTipoDato);

        JLabel lblDireccion = new JLabel("Dirección:");
        lblDireccion.setFont(fuenteLabels);
        lblDireccion.setBounds(600, 180, 200, 30);
        add(lblDireccion);

        lblDireccionDato = new JLabel(" ");
        lblDireccionDato.setBounds(600, 220, 600, 60);
        configurarEstiloCaja(lblDireccionDato, fuenteDatos, bordeCaja, colorFondoCaja);
        add(lblDireccionDato);

        JLabel lblRenta = new JLabel("Renta mensual:");
        lblRenta.setFont(fuenteLabels);
        lblRenta.setBounds(80, 330, 250, 30);
        add(lblRenta);

        lblRentaDato = new JLabel(" ");
        lblRentaDato.setBounds(80, 370, 430, 60);
        configurarEstiloCaja(lblRentaDato, fuenteDatos, bordeCaja, colorFondoCaja);
        add(lblRentaDato);

        btnRegistrar = new JButton("Registrar Arrendatario");
        btnRegistrar.setBounds(850, 500, 350, 60);
        btnRegistrar.setFont(new Font("Arial", Font.PLAIN, 22));
        btnRegistrar.setBackground(new Color(140, 140, 140));
        btnRegistrar.setFocusable(false);
        add(btnRegistrar);
        
        
        cbPropiedades.addActionListener(e -> {
            
            
            String seleccion = (String) cbPropiedades.getSelectedItem();
            InmuebleSalidaDTO inmueble = obtenerDTO(seleccion);
            inmuebleSeleccionado = inmueble;
            lblTipoDato.setText(inmueble.tipo());
            lblDireccionDato.setText(inmueble.direccion());
            lblRentaDato.setText(inmueble.rentaMensual().toString());

        });
        
        btnRegistrar.addActionListener(e -> {
            frame.irARegistroConDatos(inmuebleSeleccionado);
        
        });
    }
    
    private void configurarEstiloCaja(JLabel label, Font fuente, LineBorder borde, Color fondo) {
        label.setFont(fuente);
        label.setBorder(BorderFactory.createCompoundBorder(borde, BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        label.setBackground(fondo);
        label.setOpaque(true);
    }

    private List<InmuebleSalidaDTO> cargarListaInmuebles() throws NegocioException{
        try{
            this.listaInmuebles = inmuebleBO.listarInmueblesDisponibles();
            return inmuebleBO.listarInmueblesDisponibles();
        }
        catch(NegocioException ex){
            throw new NegocioException(ex.getMessage());
        }
    }
    
    private List<String> stringInmuebles(){
        List<String> listaString = new ArrayList<>();
        for (InmuebleSalidaDTO inmueble: listaInmuebles) {
            listaString.add(inmueble.direccion());
        }
        
        return listaString;
    }

    private InmuebleSalidaDTO obtenerDTO(String calle) {
        for (InmuebleSalidaDTO inmueble: listaInmuebles) {
            if (inmueble.direccion().equalsIgnoreCase(calle)) {
                return inmueble;
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
